# Generated by Django 4.2.5 on 2023-12-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meteo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meteo',
            old_name='temperaature',
            new_name='temperature',
        ),
    ]
